export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const CREATE_PRODUCTS_FAIL = "CREATE_PRODUCTS_FAIL";

export const BOOK_TABLE_SUCCESS = "BOOK_TABLE_SUCCESS";
export const BOOK_TABLE_FAIL = "BOOK_TABLE_FAIL";

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_PRODUCTS_FAIL = "UPDATE_PRODUCTS_FAIL";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const DELETE_PRODUCTS_FAIL = "DELETE_PRODUCTS_FAIL";

export const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST";
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
export const PRODUCTS_LIST_FAIL = "PRODUCTS_LIST_FAIL";

export const PRODUCTS_DETAILS_REQUEST = "PRODUCTS_DETAILS_REQUEST";
export const PRODUCTS_DETAILS_SUCCESS = "PRODUCTS_DETAILS_SUCCESS";
export const PRODUCTS_DETAILS_FAIL = "PRODUCTS_DETAILS_FAIL";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

// AUTHENTICATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
