export const items = [
  {
    id: 698756,
    title: "Set meal for 1",
    description:
      "1 poppadom & 1 spiced onions, 1 (chicken or vegetable pakora), 1 traditional curry, 1 (Nan or rice or chips or 2 chapatties)",
    price: 10.45,
    choose1: ["chicken pakora", "vegetable pakora"],
    choose2: [
      "bhoone",
      "chasni",
      "dopiaza",
      "garlic chilli",
      "jalfrezi",
      "karahi",
      "korma",
      "madras",
      "patia",
      "saag",
    ],
    choose3: [
      "chicken",
      "chicken tikka",
      "king prawns",
      "lamb",
      "mixed vegetables",
      "jalfrezi",
      "karahi",
      "korma",
      "madras",
      "patia",
      "saag",
    ],
    choose4: [
      "2 chapatties",
      "boll rice",
      "chips",
      "garlic nan",
      "peshwar nan",
      "pilau rice",
      "plain nan",
    ],
  },
  {
    id: 964642,
    title: "Set meal for 2",
    description:
      "2 poppadoms & 1 spiced onions, 2 (chicken or vegetable pakora), 2 traditional curries, 2 (Nan or rice or chips or 2 chapatties)",
    price: 19.95,
    choose1: ["chicken pakora", "vegetable pakora"],
    choose2: [
      "bhoone",
      "chasni",
      "dopiaza",
      "garlic chilli",
      "jalfrezi",
      "karahi",
      "korma",
      "madras",
      "patia",
      "saag",
    ],
    choose3: [
      "chicken",
      "chicken tikka",
      "king prawns",
      "lamb",
      "mixed vegetables",
      "jalfrezi",
      "karahi",
      "korma",
      "madras",
      "patia",
      "saag",
    ],
    choose4: [
      "2 chapatties",
      "boll rice",
      "chips",
      "garlic nan",
      "peshwar nan",
      "pilau rice",
      "plain nan",
    ],
  },
  {
    id: 687964,
    title: "Set meal for 4",
    description:
      "4 poppadoms & 1 spiced onions, mixed platter for 4(chicken chaat,veg chicken & mushroom pakora), 4traditional curries, 4 (Nan or rice or chips or 2 chapatties)",
    price: 35.95,
    choose1: ["chicken pakora", "vegetable pakora"],
    choose2: [
      "bhoone",
      "chasni",
      "dopiaza",
      "garlic chilli",
      "jalfrezi",
      "karahi",
      "korma",
      "madras",
      "patia",
      "saag",
    ],
    choose3: [
      "chicken",
      "chicken tikka",
      "king prawns",
      "lamb",
      "mixed vegetables",
      "jalfrezi",
      "karahi",
      "korma",
      "madras",
      "patia",
      "saag",
    ],
    choose4: [
      "2 chapatties",
      "boll rice",
      "chips",
      "garlic nan",
      "peshwar nan",
      "pilau rice",
      "plain nan",
    ],
    extra_money_king_pawns: 5.0,
    extra_money_lamb: 1.5,
    extra_money_garlic_nan: 0.5,
    extra_money_peshwar_nan: 1.5,
  },
];
